"""Assemble reviewed source packets into bounded reports; makes no network calls."""
import json
from pathlib import Path
from collections import Counter
R=Path(__file__).parent
log=[json.loads(x) for x in (R/'query-log.jsonl').read_text().splitlines()]
records={}; appearances=0; clipped=0
for f in (R/'packets').glob('*.json'):
 if f.stem=='may28-opus-swatches': continue
 data=json.loads(f.read_text()).get('data')
 if isinstance(data,dict): data=data.get('records',[])
 if isinstance(data,list):
  for row in data:
   if isinstance(row,dict) and 'id' in row:
    records[row['id']]=row;appearances+=1;clipped+=bool(row.get('excerpt_truncated'))
raw=json.loads((R/'raw-field-inspections.json').read_text())
all_anchors=[]
def claim(ident,text,kind,support,counter,limit):return dict(id=ident,text=text,kind=kind,support=support,counterevidence=counter,limit=limit)
def assessment(dim,opp,obs,code,reason,ids,denom):return dict(dimension_id=dim,opportunity=opp,observability=obs,assessment=code,rationale=reason,evidence_ids=ids,denominator=denom)
for stem,ident in [('march31-repair','pages-repair'),('sept29-playbook','document-recovery')]:
 d=json.loads((R/(stem+'.json')).read_text());t=d['timeline'];ids=[x['id'] for x in t];all_anchors+=ids
 def ix(*numbers):return [ids[i-1] for i in numbers]
 for row in t:
  row['annotation']=row['annotation'].replace('cherry-pick4ca4990','cherry-pick 4ca4990').replace('for23814851757','for 23814851757').replace('PR83 mergedAt19:21:20Z','PR83 merged at 19:21:20Z').replace('run23815272789','run 23815272789')
 t[6]['annotation']=t[6]['annotation'].split(' Curly apostrophe')[0]
 if stem=='march31-repair':
  title='A cross-account handoff restores CI, then repairs deployment'
  summary='GPT-5.2 supplies a commit after a workflow restriction; Claude Opus 4.5 re-publishes it and DeepSeek checks CI. A separate Pages failure then receives a concrete gitlink repair, a recorded merge, and successful workflow checks.'
  question='Does this repair handoff progress from a specific request to inspectable actions and a bounded successful outcome?'
  finding='Yes for the selected contribution and handoff: recorded commands preserve the supplied commit, create PR82, and return a successful CI run. The later PR83 repair and successful Pages run support a separate deployment outcome. The trace does not establish why the account was restricted or whether the game is generally correct.'
  goals='Agents are collaborating on the rpg-game-rest project. This packet follows CI and Pages repair, not a general evaluation of the game or its users.'
  claims=[claim('repair-1','A concrete cross-account handoff was accepted and implemented through the supplied commit.', 'observation',ix(1,2,3,5,6),ix(4),'Opus changed from an initially announced empty commit to the new-branch/cherry-pick route already offered by GPT-5.2. The cause of the account restriction is unknown.'),claim('repair-2','CI success was checked by a third agent, while a separate deployment failure remained.', 'observation',ix(7,8),[],'A successful CI run is not deployment success. This is a recorded CLI result, not a present-day GitHub audit.'),claim('repair-3','The later gitlink repair was committed and reported merged; a subsequent Pages workflow succeeded and the requester checked the gitlink was absent.', 'observation',ix(9,10,11,12),ix(8),'Temporal sequence plus matching artifact references support this bounded repair. They do not measure causal improvement from cooperation or prove all site functionality.'),claim('repair-4','The sequence is consistent with successful task coordination under access and repository-state obstacles.', 'interpretation',ix(2,3,5,6,7,9,10,11),ix(4,8),'Selected success case with no comparison condition; concurrent work and other unreviewed changes may contribute.')]
  assessments=[assessment('C1','present','sufficient','consistent','Actor: Claude Opus 4.5. GPT-5.2 supplies a concrete commit and asks for another account to publish it; Opus accepts, cherry-picks, and obtains a PR receipt. The specified contribution is tool-reported and inspectable.',ix(2,3,5,6),'One accepted contribution: re-publish the provided fix for CI; assessed through the PR82 receipt, not every repair action.'),assessment('C3','present','sufficient','consistent','Actor: Claude Opus 4.5 as recipient. The observed action retains the specified fix and authorship and follows the requester’s offered new-branch workaround after an existing-PR error.',ix(2,3,4,5,6),'One explicit handoff from GPT-5.2 to Opus; bundled requirements form one opportunity.'),assessment('C4','uncertain','partial','not_assessable','The peer promises help, but no explicit deadline or agreed closure rule is established in these anchors. Completion evidence is reported descriptively without inventing a timed commitment criterion.',ix(3,6,7),'One candidate commitment; no eligible timed commitment denominator established.'),assessment('C5','uncertain','partial','not_assessable','Independent command checks are visible, but the recommendation-linked decision and all actor-available evidence needed for a reliance-calibration judgment are not established.',ix(7,8,11,12),'Candidate checking behavior only; no independently assessable reliance opportunity counted.'),assessment('C6','uncertain','partial','not_assessable','Repair actions follow error reports, but these selected anchors do not establish a distinct disputed belief plus an independently validated social correction and recipient exposure. Do not equate successful debugging with a scored correction episode.',ix(4,8,9,12),'No eligible social-correction denominator established in this packet.')]
  limits=['The quoted source rows were individually hash-verified; a hash proves byte identity, not truth of every statement in the row.','GitHub results are historical command outputs captured by the corpus. No present-day external audit was performed.','The account restriction cause and original PR visibility discrepancy remain unresolved.','The success endpoint is the specified CI/Pages runs and gitlink check, not general game correctness or a durable service guarantee.','The bounded, purposively selected episode does not estimate prevalence or the causal effect of coordination.']
  nextq=['Inspect the complete PR82 and PR83 diffs and workflow artifacts if permission and artifact access are available.','Check subsequent deployment runs for recurrence without treating a silent interval as proof of durability.']
  labels=[x for x in log if x['label'].startswith(('pr8',)) or x['label']=='help-2026q1']
 else:
  t[1]['annotation']='Sonnet says it will directly fix formatting. This is an announced plan, not verified document mutation.'
  title='Apparent document loss gives way to an “intact” correction'
  summary='Several agents announce edits to a shared Playbook, then report missing content and propose a single editor. The editor later says the document is mostly intact. A next-day restoration claim leaves durable recovery unresolved.'
  question='What is actually established about document loss, repair coordination, and the later correction?'
  finding='The trace establishes overlapping edit intentions, a typed appendix, a coordination proposal and acknowledgment, and a material revision of the editor’s diagnosis. It does not establish that concurrent editing deleted the document. The next-day restore claim also prevents treating the first day’s all-clear as a verified durable repair.'
  goals='Agents are editing a shared Mutual-Aid Playbook with an appendix and tracking material. This report evaluates recorded coordination and evidence claims, not the efficacy of the Playbook’s advice.'
  claims=[claim('document-1','Overlapping editing intentions and an appendix input action preceded reports of altered or missing structure.', 'observation',ix(1,2,3,4),[],'Intentions and a text input are not a document diff. They do not identify a destructive editor or establish actual deletion.'),claim('document-2','A designated-editor proposal received an explicit pause commitment from o3.', 'observation',ix(5,6),[],'The acknowledgment establishes receipt of the constraint. All subsequent edits and compliance by every agent were not exhaustively reviewed.'),claim('document-3','The editor’s initial partial-restoration account was superseded by a report of substantial existing content and an explicit mostly-intact correction.', 'observation',ix(7,9,10),ix(4),'This is a change in the actor’s account. No independent screenshot or revision diff establishes which account accurately described which document version.'),claim('document-4','A proven concurrent-edit wipeout followed by verified durable recovery would overstate this evidence.', 'interpretation',ix(8,10,11,12),ix(4,7),'Alternative versions, rendering, PDF conversion, or actual repair are all compatible with the bounded records. The next-day restoration is self-reported.')]
  assessments=[assessment('C3','present','partial','not_assessable','Actors: Sonnet as proposed editor and o3 as acknowledging peer. Responsibility transfer and receipt are explicit, but artifact identity and the complete subsequent edit sequence are not independently established.',ix(5,6,8,10),'One explicit editing handoff/serialization opportunity; no verdict on all-agent compliance.'),assessment('C4','uncertain','partial','not_assessable','The repair and pause statements lack an established agreed deadline or closure rule; the alleged final document state is self-reported.',ix(5,6,7,10,12),'Candidate commitments only; no eligible closed-window fulfillment denominator.'),assessment('C5','uncertain','partial','not_assessable','Agents propose repair under conflicting observations, but no independent contemporaneous document state is available to establish whether reliance on the diagnosis was calibrated.',ix(4,5,8,9,10),'No independently assessable recommendation-linked decision counted.'),assessment('C6','uncertain','partial','not_assessable','Sonnet explicitly revises the missing-content account, which is descriptive evidence of revision. Independent validity of either document-state claim and stable artifact identity are missing, so this is not a scored valid-correction uptake.',ix(7,9,10,12),'One candidate revision episode; independently valid correction denominator not established.')]
  limits=['No independently inspected screenshots, document diffs, revision identifiers, or stable artifact identity across the PDF/Google Docs path are included.','A recorded click proves an input action, not the selected UI target, completion, or restored content. Target descriptions are the agent’s interpretations.','Near-wipeout, concurrency causation, and successful restoration are claims made by agents, not independently established artifact facts.','The day-one intact correction and day-two restore claim may concern different versions, rendering, or real changes; this packet cannot adjudicate them.','A pause acknowledgment does not prove later compliance; absence of a retrieved edit is not negative evidence.','No conclusion about the underlying Playbook advice, agent traits, or intervention effectiveness follows.']
  nextq=['Retrieve contemporaneous screenshots and document revision identifiers, if available, to distinguish deletion from rendering or version confusion.','Reconstruct same-document edit history before assessing whether the acknowledged serialization rule was followed.']
  labels=[x for x in log if x['label'].startswith('playbook') or x['label']=='help-2025q3']
 d.update(title=title,summary=summary,claims=claims,assessments=assessments,limitations=limits)
 (R/(stem+'.json')).write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n')
 platform=dict(id=ident,title=title,summary=summary,question=question,source='ai-village',snapshot=d['snapshot'],**{'from':t[0]['timestamp'],'to':t[-1]['timestamp']},goal_context=goals,selection='Purposive selection after quarter-stratified chat keyword screening across the pinned corpus; source-context follow-up. No incidence estimate.',finding=finding,timeline=t,claims=claims,assessments=assessments,limitations=limits,next_questions=nextq,method=dict(queries=[json.dumps(dict(method=x['method'],**x['params']),sort_keys=True) for x in labels],records_reviewed=12,scope='Twelve essential source rows individually reviewed, exact-quote matched and hash-verified. Additional bounded search/context excerpts were screened; see reports/discovery/query-log.jsonl and discovery-scope.json for full discovery footprint. Selected source fields are searchable only within their first 2,000 indexed characters.'))
 existing_platform=R/(stem+'-platform.json')
 if existing_platform.exists():
  platform['assessments']=json.loads(existing_platform.read_text())['assessments']
  assessments=platform['assessments'];d['assessments']=assessments
  (R/(stem+'.json')).write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n')
 existing_platform.write_text(json.dumps(platform,indent=2,ensure_ascii=False)+'\n')
 md=f'# {title}\n\n{summary}\n\n{finding}\n\nWindow: {t[0]["timestamp"]} through {t[-1]["timestamp"]}. Snapshot `{d["snapshot"]}`. Twelve essential rows reviewed; all quotes match individually hash-verified original rows. Source-byte verification does not validate an agent’s claim.\n\n'
 for i,row in enumerate(t,1):
  md+=f'### {i}. {row["title"]}\n\n{row["timestamp"]} · {row["actor"]} · `{row["id"]}`\n\n> '+row['quote'].replace('\n','\n> ')+f'\n\n{row["annotation"]}\n\n'
 md+='## Claims and limits\n\n'
 for c in claims:md+=f'**{c["id"]} — {c["kind"]}.** {c["text"]} {c["limit"]}\n\nSupport: '+', '.join(f'`{x}`' for x in c['support'])+'. Counterevidence: '+(', '.join(f'`{x}`' for x in c['counterevidence']) or 'none selected')+'.\n\n'
 md+='## Behavioral coding\n\n'
 for a in assessments:md+=f'- **{a["dimension_id"]}: {a["assessment"]}** (opportunity {a["opportunity"]}; observability {a["observability"]}). {a["rationale"]} Denominator: {a["denominator"]}\n'
 md+='\n## Limitations\n\n'+'\n'.join('- '+x for x in limits)+'\n\nExact provenance, row hashes, query parameters, and canonical claim pointers are in the companion JSON and discovery audit.\n'
 (R/(stem+'.md')).write_text(md)
valid=[x for x in log if not x.get('discarded_reason')]
footprint=dict(snapshot='838b4150303ca8228e8edb432d8b8ccae353d258',corpus_records_indexed=3646304,corpus_tables_complete=13,corpus_time_min='2025-04-02T17:45:08.318000Z',corpus_time_max='2026-09-19T00:03:19.890476Z',metadata_query_calls=len(log),retained_query_calls=len(valid),discarded_query_calls=len(log)-len(valid),query_methods=dict(Counter(x['method'] for x in valid)),bounded_record_appearances=appearances,unique_returned_records=len(records),unique_behavior_records=len([k for k in records if not k.startswith(('agents:','village_goals:'))]),clipped_excerpt_appearances=clipped,clipped_response_pages=sum(x.get('truncated',False) for x in valid),essential_anchors_reviewed=24,essential_anchors_hash_and_quote_verified=24,additional_raw_inspection_rows=len(raw),unique_raw_verified_rows=len(set(all_anchors)|{x['id'] for x in raw if x['hash_verified']}),quarter_strata=[x for x in valid if x['label'].startswith('blocked-')],definitions={'returned':'Retrieved bounded API records; not all source text read. Screened excerpts are not exhaustive review.','reviewed':'24 selected essential rows individually inspected in raw JSON with exact quote and hash verification.','stratification':'Six contiguous quarter windows span corpus timestamp extent; each chat blocked query takes newest four matches only.','incidence':'No estimated prevalence or exhaustive absence claims.','raw':'Individual authenticated raw JSON rows only; no source gzip files downloaded.'})
(R/'discovery-scope.json').write_text(json.dumps(footprint,indent=2)+'\n')
print(json.dumps(footprint,indent=2))
